### ISSUE TITLE
output colnames for data frame producing funs

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#230] opened 2020-01-13 12:25 UTC
For functions that return a data frame we need to check if the output column names make sense.

**Comment by krlmlr** [comment] 2020-01-14 08:43
This might need a closer look, reopening.

**Comment by krlmlr** [comment] 2020-01-14 08:44
Is this a duplicate of #227?

**Comment by krlmlr** [comment] 2020-01-24 09:30
Should be good now.

**Closed by krlmlr** 2020-01-24 09:30 UTC
